name: Deploy to EC2

on:
  push:
    branches:
      - main  # only deploy on main branch
  workflow_dispatch: # allow manual triggers

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    environment:
      name: mlops-ec2-staging  # use your environment
    steps:
      # 1. Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up SSH for EC2
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ vars.EC2_HOST_IP }}" >> ~/.ssh/known_hosts

      # 3. Deploy script on EC2
      - name: Run deployment on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ vars.EC2_HOST_IP }} << 'EOF'
            cd /home/ubuntu/mlops_project || exit
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF

      # 4. Optional: Notify on successful deployment
      - name: Deployment success
        run: echo "Deployment completed on EC2!"
